### ISSUE TITLE
Implicite Geom invalid

### ISSUE THREAD

**Issue by phanemy** [tudelft3d/CityGML-schema-validation#3]
Hello, i would like to know why my citygml isn't valid, the validator said ImplicitGeometry isn't valid, but regarding the official spec on ogc and schema on opengis, it looks like i'm good.

You'r validator are used by many people so i would like to know where i'm wrong :)

Here is my citygml, a zip containing the file is also provided at the end:
![image](https://user-images.githubusercontent.com/24206584/96259643-30b05f00-0fbe-11eb-8058-a0b464b12f38.png)

Implicite geom on citygml spec

![Capture](https://user-images.githubusercontent.com/24206584/96259263-a2d47400-0fbd-11eb-8563-3a1bd79afc0f.PNG)

[Export.zip](https://github.com/tudelft3d/CityGML-schema-validation/files/5391591/Export.zip)

**Comment by hugoledoux** [comment]
My validator doesn't anything but wrap the OGC CityGML v2 schemas into a web-service, and returns the error(s) to the user. So don't shoot the messenger please. Better to ask the OGC CityGML specialists about the error.

But I see several errors: remove `core:` since your default namespace has no name; `mimetype` is there twice, etc.
